### ISSUE TITLE
Initial Roadmap

### ISSUE THREAD

**Issue by scribblemaniac** [scribblemaniac/RenderChan-Blender-Plugin#1]
These are the things that need to get done before the official first 'release':
- [x] Blender sequence editor add menu option
- [x] Update dependencies on file load
- [x] Import rendered images in the File > Import menu (as assets).
- [x] Refresh render action for sequence editor
- [x] Refresh render action for uv image editor 
- [x] Render file with RenderChan from within Blender
- [x] Add necessary features to RenderChan (dry running mostly)
- [x] Contextual checks for refresh buttons

The goal is to have all of this done sometime in January (though it may be later depending on how busy I am). Here are some things that will not be done right now, but will probably be worked on in the future:
- Import rendered movies or image sequences in the File > Import menu (as assets).
- Display RenderChan output in the info panel
- Background rendering
- Support for selecting multiple files
- Icons
- Graphical rendering
- Closer integration with Blender (replacing some existing Blender functions)
